### ISSUE TITLE
BelongsToMany Doesn't Cache When Using Laravel Nova

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-model-caching#278]
I just want to share my experinece with this issue. I just faced the BelongsToMany relationship issue using laravel and Nova. it doesn't update redis on save or update or create using Nova. I have to flush redis to see changes made by laravel nova. But when i use disableCache() on my models, it's working fine. But almost all my models using BelongsToMany relationships. So no point to use this package if it's not going to cache my models :) It might be related with the events between nova and models? Maybe this package doesn't regionise Nova events to trigger updates on redis. 

Details about the issue:
I got Work and Service models. It's many to many relationships. Work has many Services and Services has Many Works.

Models in project looks like: 
Work Model
```php
class Work extends Model implements HasMedia
{
    use HasImage, HasTranslate, Cachable;

    public $translatable = ['client', 'project'];
    protected $collection = 'slider';

    protected $casts = [
        'date' => 'datetime',
    ];

    public function services()
    {
        return $this->belongsToMany(Service::class);
    }
}
```

Service Model
```php
class Service extends Model
{
    use HasTranslate, HasSlug, Cachable;

    public $translatable = ['name', 'description'];

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }

    public function works()
    {
        return $this->belongsToMany(Work::class);
    }
}
```

Works table
```php
    public function up()
    {
        Schema::create('works', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->json('client');
            $table->json('project');
            $table->date('date');
            $table->string('country');
            $table->string('url')->nullable();
            $table->timestamps();
        });
    }
```

Services table
```php
    public function up()
    {
        Schema::create('services', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->json('name');
            $table->json('description');
            $table->string('slug')->unique();
            $table->string('icon');
            $table->timestamps();
        });
    }
```

Service Work pivot table
```php
    public function up()
    {
        Schema::create('service_work', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('service_id')->unsigned();
            $table->integer('work_id')->unsigned();
        });
    }
```

Laravel : 5.8.30
Redis server v=5.0.5 
Laravel Nova 2.0.9

I hope this help you to figure out the issue.  

Update: 
I just notice the key names in redis is a bit weird. 

xxx:tag:genealabs:laravel-model-caching:mysql:nemrut:appservice:key,

i believe there should be : between app and service so it should looks like 

xxx:tag:genealabs:laravel-model-caching:mysql:nemrut:app:service:key, 

is key naming working correctly? maybe shoud check that out.

_Originally posted by @nemrutco in https://github.com/GeneaLabs/laravel-model-caching/issues/127#issuecomment-520214081_

**Comment by mikebronner** [comment]
@nemrutco Let's continue the discussion here.

**Comment by tuseroni** [comment]
i'm having this issue as well, least i think they are related. i have the following model:

class products extends syncableBase
{
    //
    
    

//     public $rememberCacheTag = 'quote_queries';
    protected $with=['exclusiveCompany','pricing','parts','attributes','attributesOverride','images','weight_sections','categories'];
    public function __construct()
    {
    }
    public function attributes()
    {
        return $this->belongsToMany('App\attributes',"productattributes","products_id","attribute_id")->withPivot(["isGroup","visibilityFormula"]);
    }
    
}

syncableBase overrides hasMany but not belongsTo and uses cacheable.

if i save an existing object (one acquired via get) there is no problems, if i save a new object without any relationships, no problems, the only problem is when i create a new object, save, sync the ids, and then save again (i don't think the separate saves are part of the issue, but if i don't do the first save it never does the sync, because there is no id for the product)

it seems the save should invalidate the cache, and given there were two saves that should doubly so

relevant part of that:

$itemsArr=[];
        $groupsArr=[];
        if(isset($input["item_attributes"]))
        {
            $itemsArr=$input["item_attributes"];
        }
        if(isset($input["group_attributes"]))
        {
            $groupsArr=$input["group_attributes"];
        }
        $ids=$itemsArr+$groupsArr;
        $obj->save();//seems laravel can't handle the sync if the object is new and doesn't have a pk, as it doesn't in the case of auto_incrementing primary keys, so i have to save, then it will have a key then i can sync and save again...
        $obj->attributes()->sync($ids);

so after doing this, i go to a list of products as follows:

$data = \App\products::orderBy('product_name', 'asc')->limit(100)->get();

and the product i just created isn't in the list, if i clear the cache it shows up, if i save the product i just created again (from the product edit screen) the product will show in the list also, don't let that limit bother you, you there are only 4 products in the database right now.

it's quite perplexing

**Comment by mikebronner** [comment]
@tuseroni @nemrutco I have noticed that Nova doesn't necessarily fire the same events as Laravel when creating or saving resources. I think that may have something to do with it. Thanks for all the information, I will be looking into Nova compatibility. I just haven't been able to get to it yet. :)

**Comment by tuseroni** [comment]
i don't THINK i'm using nova, here are my requires:

"require": {
        "php": "^7.1.3",
        "ckfinder/ckfinder-laravel-package": "v3.4.5.1",
        "fideloper/proxy": "^4.0",
        "genealabs/laravel-model-caching": "^0.6.1",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "predis/predis": "^1.1",
        "watson/rememberable": "^3.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },

so my problem MIGHT not be related to his or both of our problems may be unrelated to nova.

**Comment by mikebronner** [comment]
@tuseroni then this should be a different issue.

**Comment by AbanoubNassem** [comment]
there is seek a problem with `Clouser` on saving with `nova` here is the error output :
```

     {
    "message": "Serialization of 'Closure' is not allowed",
    "exception": "Exception",
    "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php",
    "line": 65,
    "trace": [
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php",
            "line": 65,
            "function": "serialize"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php",
            "line": 121,
            "function": "put",
            "class": "Illuminate\\Cache\\FileStore",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Cache/Repository.php",
            "line": 355,
            "function": "forever",
            "class": "Illuminate\\Cache\\FileStore",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Cache/Repository.php",
            "line": 418,
            "function": "forever",
            "class": "Illuminate\\Cache\\Repository",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php",
            "line": 357,
            "function": "rememberForever",
            "class": "Illuminate\\Cache\\Repository",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php",
            "line": 292,
            "function": "__call",
            "class": "Illuminate\\Cache\\CacheManager",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php",
            "line": 227,
            "function": "retrieveCachedValue",
            "class": "GeneaLabs\\LaravelModelCaching\\CachedBelongsToMany",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php",
            "line": 97,
            "function": "cachedValue",
            "class": "GeneaLabs\\LaravelModelCaching\\CachedBelongsToMany",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php",
            "line": 588,
            "function": "get",
            "class": "GeneaLabs\\LaravelModelCaching\\CachedBelongsToMany",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php",
            "line": 429,
            "function": "getResults",
            "class": "Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php",
            "line": 401,
            "function": "getRelationshipFromMethod",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php",
            "line": 333,
            "function": "getRelationValue",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
            "line": 1546,
            "function": "getAttribute",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Support/Arr.php",
            "line": 148,
            "function": "offsetExists",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Support/helpers.php",
            "line": 162,
            "function": "exists",
            "class": "Illuminate\\Support\\Arr",
            "type": "::"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Fields/Field.php",
            "line": 253,
            "function": "data_get"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Fields/Field.php",
            "line": 234,
            "function": "resolveAttribute",
            "class": "Laravel\\Nova\\Fields\\Field",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php",
            "line": 60,
            "function": "resolve",
            "class": "Laravel\\Nova\\Fields\\Field",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php",
            "line": 176,
            "function": "Illuminate\\Support\\{closure}",
            "class": "Illuminate\\Support\\HigherOrderCollectionProxy",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php",
            "line": 61,
            "function": "each",
            "class": "Illuminate\\Support\\Collection",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/ResolvesFields.php",
            "line": 250,
            "function": "__call",
            "class": "Illuminate\\Support\\HigherOrderCollectionProxy",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/ResolvesFields.php",
            "line": 172,
            "function": "resolveFields",
            "class": "Laravel\\Nova\\Resource",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/ResolvesFields.php",
            "line": 183,
            "function": "updateFields",
            "class": "Laravel\\Nova\\Resource",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/FillsFields.php",
            "line": 35,
            "function": "updateFieldsWithoutReadonly",
            "class": "Laravel\\Nova\\Resource",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Http/Controllers/ResourceUpdateController.php",
            "line": 34,
            "function": "fillForUpdate",
            "class": "Laravel\\Nova\\Resource",
            "type": "::"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php",
            "line": 29,
            "function": "Laravel\\Nova\\Http\\Controllers\\{closure}",
            "class": "Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php",
            "line": 349,
            "function": "transaction",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
            "line": 239,
            "function": "__call",
            "class": "Illuminate\\Database\\DatabaseManager",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Http/Controllers/ResourceUpdateController.php",
            "line": 43,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },
        {
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 219,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 176,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 680,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 130,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Http/Middleware/Authorize.php",
            "line": 18,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\Authorize",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Http/Middleware/BootTools.php",
            "line": 20,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\BootTools",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Http/Middleware/DispatchServingNovaEvent.php",
            "line": 20,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php",
            "line": 43,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Http/Middleware/Authenticate.php",
            "line": 31,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 75,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php",
            "line": 58,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\AuthenticateSession",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 56,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 105,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 682,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 657,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 623,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 612,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 176,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 130,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/nova/src/Http/Middleware/ServeNova.php",
            "line": 26,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\ServeNova",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php",
            "line": 65,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Barryvdh\\Debugbar\\Middleware\\InjectDebugbar",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 62,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 105,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 151,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 116,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Volumes/Data/websites/testwebsite/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/abanoub/.composer/vendor/laravel/valet/server.php",
            "line": 158,
            "function": "require"
        }
    ]
}
```

**Comment by mikebronner** [comment]
@AbanoubNassem Thanks for the additional info! Currently this package is not Nova compatible, but it is definitely something we want to fix.

**Comment by d8vjork** [comment]
Is still this in progress? I think we're facing the same issue, any workaround for the Nova part only?

**Comment by mikebronner** [comment]
@d8vjork Hmm, was hoping the PR from @dmason30 would have fixed it. I need to get review a few other things and will rerun tests in the coming days. If you could submit a PR with a failing test, that would help me out tremendously.

**Comment by d8vjork** [comment]
@mikebronner Yeah, will definitely do once I've some time

**Comment by mikebronner** [comment]
@olliescase happy to entertain a PR for this if you can. I currently don't use Nova in any of my projects.

**Comment by ekandreas** [comment]
This is fixed in 0.12.5 saving pivot sync.

**Comment by olliescase** [comment]
Great! Will test it out on our project. Thanks @ekandreas for the heads up and @d8vjork for the fix. (And sorry @mikebronner for not responding - I had it in my head that I had)

**Comment by mikebronner** [comment]
Closing this issue for now.

**Comment by JanKrb** [comment]
Still having the same bug with nova 4.15 and package version 0.12.5. Anybody else here?
