### ISSUE TITLE
Pagination count query wont get cached

### ISSUE THREAD

**Issue by jurrid** [GeneaLabs/laravel-model-caching#85]
## Environment
Laravel Version: *5.6.3*
Laravel Model Caching Package Version: *0.2.33*
PHP Version: *7.2.0*
Homestead Version: *-*
Operating System & Version: *macOs High Sierra 10.13.3*

## Stack Trace

When using the paginate query there is a count query that not get cached

```php
$articles = Article::paginate(30);
```

In the debug bar you see this query:

```mysql
select count(*) as aggregate from articles
```

**Comment by mikebronner** [comment]
@jurrid Thanks for reporting. I will look into this ASAP. :)

**Comment by mikebronner** [comment]
Looking into this now.

**Comment by mikebronner** [comment]
Fix is implemented in next patch, coming in a few minutes.

**Comment by mikebronner** [comment]
Should be fixed in version 0.2.35. Please let me know if it works for you now. Thanks! :)

**Comment by jurrid** [comment]
There is one little issue now.
The extra query is now cached but the pagination buttons are not working.

```
{{ $articles->links() }}
````

If you click to the second page the offset in the next page is stuck on the one thats is cached.

**Comment by mikebronner** [comment]
Hmm, thanks for following up with me. I'll look into this.

**Comment by mikebronner** [comment]
Hi @jurrid, I added some pagination tests, and the links provided seem all correct to me. Any chance you customized your pagination somehow, or are passing in parameters to the pagination command?
Take a look at the tests I added here (https://github.com/GeneaLabs/laravel-model-caching/commit/31c0b12e916ae5b8643c14d980e25184a080d162) and let me know if I missed something?

Thanks!

**Comment by dyzajash** [comment]
I have the same issue with pagination. 

Clicking buttons redirects to `my-route?page=5`, but data is still from page=1. 

Cache server: redis
Laravel: 5.5
PHP: 7.1

**Comment by mikebronner** [comment]
I have been able to reproduce this issue now. Working on identifying the cause and then a fix, hopefully today.

**Comment by mikebronner** [comment]
This is now fixed in release 0.2.45. Please let me know how it works for you guys. Thanks for being patient and reporting it!

**Comment by dyzajash** [comment]
0.2.45 is not working with Laravel 5.5

```
    - Installation request for genealabs/laravel-model-caching ^0.2.45 -> satisfiable by genealabs/laravel-model-caching[0.2.45].
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - genealabs/laravel-model-caching 0.2.45 requires fico7489/laravel-pivot ^2.2 -> satisfiable by fico7489/laravel-pivot[2.2.4, 2.2.5].
    - fico7489/laravel-pivot 2.2.4 requires illuminate/database 5.6.* -> satisfiable by illuminate/database[v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
    - fico7489/laravel-pivot 2.2.5 requires illuminate/database 5.6.* -> satisfiable by illuminate/database[v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
```

**Comment by mikebronner** [comment]
Ack! Will get that fixed. Thanks for alerting me.

**Comment by mikebronner** [comment]
@dyzajash This should now be fixed in version 0.2.46.

**Comment by scottgrayson** [comment]
@mikebronner 0.2.46 worked for me 👍

**Comment by mikebronner** [comment]
@scottgrayson woot! Thanks for verifying! :) @dyzajash Please re-open if this still doesn't work for you.

**Comment by niladam** [comment]
@mikebronner in 0.2.55 this is still an issue and pagination still doesn't work.

This is my code:

```php
    public function index()
    {
        $model = Mymodel::paginate('', ['*'], 'pages');

        return view('model.show', ['model' => $model]);
    }
```

**Comment by mikebronner** [comment]
I will take a look at this, thanks!

**Comment by mikebronner** [comment]
I believe your pagination syntax is incorrect? This is the `paginate()` method signature:

```php
public function paginate($perPage = 15, $columns = ['*'], $pageName = 'page', $page = null)
```

**Comment by niladam** [comment]
@mikebronner The pagination isn't incorrect and it doesn't really matter if i use `Mymodel::paginate();` my code. The code i was using was `Mymodel::paginate('20', [*], 'pagename');` because i'm actually overriding `$perPage` and `$pageName` :)

**Comment by mikebronner** [comment]
@niladam thanks, that makes more sense ... in the example above you left perPage as an empty string. I will test again, but didn't have any issues when I tested last weekend. I'll get back to you this weekend. :)

**Comment by mikebronner** [comment]
@niladam I'm sorry, I cannot replicate the issue based on the information you provided so far. If this persists, please open a new issue and make sure to add a complete stack trace along with the eloquent query that broke it.
